#!/bin/bash

set -e

proj_dir=~/Projects

usage() {
	echo "Usage: $(basename "$0") [project-kind] [project-name]" >&2
	echo "project-kinds:            "
	echo "$(ls ~/Projects/quick_proj/project_kinds)"
	exit 1
}

if [ "$#" -ne 2 ]
then
	usage
fi

if [ -d "$proj_dir/quick_proj/project_kinds/$1" ]
then
    if [ -d  "$proj_dir/$2" ]
    then
	echo "project already exists"
	exit
    fi
    mkdir $proj_dir/"$2"
    cp -r $proj_dir/quick_proj/project_kinds/"$1"/* $proj_dir/"$2"
    pushd $proj_dir/"$2"
    mv {,.}gitignore

    if [ $1 == "fpga" ]
    then
	mv app_name.vhd $2.vhd
    fi

    find . -type f -exec sed -i "s/app_name/${2}/g" {} \;
    popd
else
    echo "failed to make project"
    usage
fi
